/* =========================================================================
   viz.js — THE VISUALIZE MODE (step-by-step animated diagrams).
   -------------------------------------------------------------------------
   HOW IT WORKS (the design):
     • An "operation" (e.g. "Stack: push & pop") is built into a list of
       FRAMES. Each frame = one stage of the animation:
           { caption, kind, model, highlight }
       - caption   : the explanation shown under the drawing.
       - kind      : which renderer to use ('stack','list','tree','bars','array').
       - model     : the data to draw (values, nodes, tree...).
       - highlight : which parts to color (the "what changed" of this step).
     • The PLAYER shows one frame at a time; Prev/Next/Play move through them.
     • RENDERERS turn a model into an SVG picture.

   To ADD an animation: write a build() function that returns { title, frames }
   and add it to the OPERATIONS list at the bottom. Nothing else changes.

   NOTE on innerHTML: the SVG strings below are generated by THIS code from
   numeric/structural data we control (never free user text), so building them
   as strings is safe. All human text (captions) is set via textContent.
   ========================================================================= */

const Viz = (function () {

  /* ---------- colors (kept in sync with the CSS theme) ---------- */
  const C = {
    fill: '#1e293b', stroke: '#475569', text: '#e2e8f0',
    active: '#f59e0b',   // the node currently being looked at
    good:   '#22c55e',   // inserted / finalized
    accent: '#6366f1',   // pointer / path
    dim:    '#64748b'
  };

  /* =====================================================================
     RENDERERS — each returns an SVG string for one frame's model.
     ===================================================================== */

  /* --- STACK: vertical boxes, growing upward, "top" marked. --- */
  function renderStack(f) {
    const vals = f.model.values, hl = f.model.highlight || {};
    const W = 320, boxW = 90, boxH = 40, x = (W - boxW) / 2;
    const baseY = 250, H = 290;
    let s = svgOpen(W, H);
    if (vals.length === 0) {
      s += text(W / 2, 140, '(empty stack)', C.dim, 14, 'middle');
    }
    vals.forEach((v, i) => {
      const y = baseY - (i + 1) * (boxH + 6);
      const color = hl[i] || C.fill;
      s += rect(x, y, boxW, boxH, color, C.stroke);
      s += text(x + boxW / 2, y + boxH / 2 + 5, v, C.text, 16, 'middle');
      if (i === vals.length - 1) s += text(x + boxW + 16, y + boxH / 2 + 5, '← top', C.accent, 13, 'start');
    });
    // base line
    s += `<line x1="${x - 10}" y1="${baseY}" x2="${x + boxW + 10}" y2="${baseY}" stroke="${C.dim}" stroke-width="3"/>`;
    return s + '</svg>';
  }

  /* --- ARRAY: horizontal boxes with index labels (used for heap array). --- */
  function renderArray(f) {
    const vals = f.model.values, hl = f.model.highlight || {}, ptr = f.model.pointers || {};
    const boxW = 44, boxH = 40, gap = 6, x0 = 20, y = 90;
    const W = Math.max(320, x0 * 2 + vals.length * (boxW + gap)), H = 170;
    let s = svgOpen(W, H);
    vals.forEach((v, i) => {
      const x = x0 + i * (boxW + gap);
      s += rect(x, y, boxW, boxH, hl[i] || C.fill, C.stroke);
      s += text(x + boxW / 2, y + boxH / 2 + 5, v, C.text, 15, 'middle');
      s += text(x + boxW / 2, y + boxH + 16, '[' + i + ']', C.dim, 11, 'middle');
      if (ptr[i]) s += text(x + boxW / 2, y - 10, ptr[i], C.accent, 12, 'middle');
    });
    return s + '</svg>';
  }

  /* --- BARS: for sorting animations. --- */
  function renderBars(f) {
    const vals = f.model.values, hl = f.model.highlight || {};
    const barW = 34, gap = 8, x0 = 20, baseY = 210, maxH = 160;
    const maxV = Math.max.apply(null, vals);
    const W = Math.max(320, x0 * 2 + vals.length * (barW + gap)), H = 240;
    let s = svgOpen(W, H);
    vals.forEach((v, i) => {
      const h = Math.round((v / maxV) * maxH);
      const x = x0 + i * (barW + gap), y = baseY - h;
      s += rect(x, y, barW, h, hl[i] || C.accent, C.stroke, 4);
      s += text(x + barW / 2, y - 6, v, C.text, 13, 'middle');
    });
    s += `<line x1="10" y1="${baseY}" x2="${W - 10}" y2="${baseY}" stroke="${C.dim}" stroke-width="2"/>`;
    return s + '</svg>';
  }

  /* --- LIST: boxes + arrows + pointer labels (head/curr/prev/new). --- */
  function renderList(f) {
    const nodes = f.model.nodes, hl = f.model.highlight || {}, ptr = f.model.pointers || {};
    const boxW = 52, boxH = 38, gap = 42, x0 = 24, y = 90;
    const W = Math.max(340, x0 * 2 + nodes.length * (boxW + gap) + 40), H = 170;
    let s = svgOpen(W, H);
    // pointer labels: {name: index}
    const byIndex = {};
    Object.keys(ptr).forEach((name) => {
      const idx = ptr[name];
      (byIndex[idx] = byIndex[idx] || []).push(name);
    });
    nodes.forEach((n, i) => {
      const x = x0 + i * (boxW + gap);
      s += rect(x, y, boxW, boxH, hl[i] || C.fill, C.stroke);
      s += text(x + boxW / 2, y + boxH / 2 + 5, n.val, C.text, 15, 'middle');
      // arrow to next
      const ax = x + boxW, ax2 = x + boxW + gap;
      if (i < nodes.length - 1) s += arrow(ax + 2, y + boxH / 2, ax2 - 2, y + boxH / 2, C.dim);
      else { // -> null
        s += arrow(ax + 2, y + boxH / 2, ax2 - 6, y + boxH / 2, C.dim);
        s += text(ax2 + 4, y + boxH / 2 + 5, '∅', C.dim, 16, 'start');
      }
      // pointer labels above
      if (byIndex[i]) {
        byIndex[i].forEach((name, k) => {
          s += text(x + boxW / 2, y - 14 - k * 16, name, C.accent, 12, 'middle');
          if (k === 0) s += text(x + boxW / 2, y - 2, '↓', C.accent, 12, 'middle');
        });
      }
    });
    return s + '</svg>';
  }

  /* --- TREE: positioned circles + edges (used for BST and heap-as-tree). --- */
  function renderTree(f) {
    const nodes = f.model.nodes, root = f.model.root, hl = f.model.highlight || {};
    // 1. assign x by in-order index, y by depth.
    const pos = {}, order = { i: 0 };
    function walk(id, depth) {
      if (id === null || id === undefined || !nodes[id]) return;
      walk(nodes[id].left, depth + 1);
      pos[id] = { xi: order.i++, depth: depth };
      walk(nodes[id].right, depth + 1);
    }
    walk(root, 0);
    const ids = Object.keys(pos);
    const dx = 60, dy = 64, x0 = 34, y0 = 34, r = 20;
    const maxXi = Math.max.apply(null, ids.map((id) => pos[id].xi).concat([0]));
    const maxD = Math.max.apply(null, ids.map((id) => pos[id].depth).concat([0]));
    const W = Math.max(320, x0 * 2 + maxXi * dx + r * 2);
    const H = Math.max(120, y0 * 2 + maxD * dy + r * 2);
    const px = (id) => x0 + pos[id].xi * dx + r;
    const py = (id) => y0 + pos[id].depth * dy + r;
    let s = svgOpen(W, H);
    // edges first
    ids.forEach((id) => {
      ['left', 'right'].forEach((side) => {
        const c = nodes[id][side];
        if (c !== null && c !== undefined && nodes[c]) {
          s += `<line x1="${px(id)}" y1="${py(id)}" x2="${px(c)}" y2="${py(c)}" stroke="${C.dim}" stroke-width="2"/>`;
        }
      });
    });
    // nodes on top
    ids.forEach((id) => {
      const color = hl[id] || C.fill;
      s += `<circle cx="${px(id)}" cy="${py(id)}" r="${r}" fill="${color}" stroke="${C.stroke}" stroke-width="2"/>`;
      s += text(px(id), py(id) + 5, nodes[id].val, C.text, 15, 'middle');
    });
    if (ids.length === 0) s += text(W / 2, H / 2, '(empty tree)', C.dim, 14, 'middle');
    return s + '</svg>';
  }

  /* ---------- tiny SVG string helpers ---------- */
  function svgOpen(w, h) {
    return `<svg viewBox="0 0 ${w} ${h}" width="100%" preserveAspectRatio="xMidYMid meet" xmlns="http://www.w3.org/2000/svg" font-family="monospace">`;
  }
  function rect(x, y, w, h, fill, stroke, rad) {
    return `<rect x="${x}" y="${y}" width="${w}" height="${h}" rx="${rad || 6}" fill="${fill}" stroke="${stroke}" stroke-width="2"/>`;
  }
  function text(x, y, t, fill, size, anchor) {
    return `<text x="${x}" y="${y}" fill="${fill}" font-size="${size}" text-anchor="${anchor || 'start'}">${t}</text>`;
  }
  function arrow(x1, y1, x2, y2, color) {
    const a = `<line x1="${x1}" y1="${y1}" x2="${x2}" y2="${y2}" stroke="${color}" stroke-width="2"/>`;
    const h = `<path d="M ${x2} ${y2} l -6 -4 l 0 8 z" fill="${color}"/>`;
    return a + h;
  }

  function renderFrame(f) {
    if (f.kind === 'stack') return renderStack(f);
    if (f.kind === 'array') return renderArray(f);
    if (f.kind === 'bars')  return renderBars(f);
    if (f.kind === 'list')  return renderList(f);
    if (f.kind === 'tree')  return renderTree(f);
    return '';
  }

  /* =====================================================================
     BUILDERS — each returns { title, titleHe, frames:[...] }.
     Kept in js/viz-ops.js for readability.
     ===================================================================== */
  const OPERATIONS = window.VIZ_OPERATIONS || [];

  /* =====================================================================
     THE PLAYER
     ===================================================================== */
  let frames = [], idx = 0, timer = null;

  function init() {
    renderList_();
    $('viz-prev').addEventListener('click', () => step(-1));
    $('viz-next').addEventListener('click', () => step(1));
    $('viz-play').addEventListener('click', togglePlay);
    $('viz-back').addEventListener('click', backToList);
  }

  /* the picker of operations */
  function renderList_() {
    const list = $('viz-list');
    list.textContent = '';
    OPERATIONS.forEach((op, i) => {
      const card = el('button', 'topic-card');
      card.appendChild(el('div', 't-title', op.title));
      if (op.titleHe) card.appendChild(el('div', 't-title-he', op.titleHe));
      card.appendChild(el('div', 't-count', op.frames.length + ' שלבים'));
      card.addEventListener('click', () => open(i));
      list.appendChild(card);
    });
  }

  function open(i) {
    const op = OPERATIONS[i];
    frames = op.frames; idx = 0;
    $('viz-title').textContent = op.title;
    $('viz-list').classList.add('hidden');
    $('viz-player').classList.remove('hidden');
    draw();
  }

  function draw() {
    const f = frames[idx];
    $('viz-stage').innerHTML = renderFrame(f);   // SVG from trusted numeric data
    $('viz-caption').textContent = bidi(f.caption);   // isolate LTR math in Hebrew text
    $('viz-step').textContent = (idx + 1) + ' / ' + frames.length;
    $('viz-prev').disabled = idx === 0;
    $('viz-next').disabled = idx === frames.length - 1;
  }

  function step(d) {
    idx = Math.min(frames.length - 1, Math.max(0, idx + d));
    draw();
  }

  function togglePlay() {
    if (timer) { stopPlay(); return; }
    $('viz-play').textContent = '⏸ עצור';
    timer = setInterval(() => {
      if (idx >= frames.length - 1) { stopPlay(); return; }
      step(1);
    }, 1400);
  }
  function stopPlay() { clearInterval(timer); timer = null; $('viz-play').textContent = '▶ הפעל'; }

  function backToList() {
    stopPlay();
    $('viz-player').classList.add('hidden');
    $('viz-list').classList.remove('hidden');
  }

  return { init: init };
})();

window.Viz = Viz;
